apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlanAdmission
metadata:
  labels:
    release.appstudio.openshift.io/auto-release: 'true'
  name: konflux-ui-demo-rpa
  namespace: bramos-tenant
spec:
  applications:
    - github-demo
  origin: bramos-tenant
  pipeline: 
    pipelineRef:
      resolver: 'git'
      params:
        - name: 'url'
          value: 'https://github.com/CryptoRodeo/konflux-examples'
        - name: 'revision'
          value: 'main'
        - name: 'pathInRepo'
          value: 'release.yml'
  policy: always-pass-policy
